#!/bin/bash

install_env(){
    pip3 install rt-thread-studio
    python3 -c "from rt_thread_studio import bsp_checker;bsp_path = '.';checker = bsp_checker.BspChecker(bsp_path);checker.check();"
    sudo apt-get -qq install libsdl2-dev scons
    wget https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
    if [ -f "gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2" ]; then
        sudo tar xvf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
    else
        echo "download toolchains failed"
    fi
}

export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin
export RTT_ROOT=$(pwd)
export RTT_CC=gcc

if [ ! -d $RTT_EXEC_PATH ]; then
    install_env
fi
